// list of all the tags
export const tagList = [
  { name: "Beginner", color: "#FF7F50" },
  { name: "Intermediate", color: "#FFD700" },
  { name: "Advanced", color: "#8A2BE2" },
  { name: "Looking for Feedback", color: "#1E90FF" },
  { name: "Help Wanted", color: "#FF4500" },
  { name: "Documentation", color: "#DAA520" },
  { name: "Tutorial", color: "#ADFF2F" },
  { name: "Article", color: "#FF69B4" },
  { name: "Machine Learning", color: "#FFB500" },
  { name: "Data Science", color: "#4595B8" },
  { name: "Web Development", color: "#3E7BB6" },
  { name: "Front-end", color: "#FF4081" },
  { name: "Back-end", color: "#333333" },
  { name: "Full Stack", color: "#00D1A1" },
  { name: "DevOps", color: "#4CAF50" },
  { name: "JavaScript", color: "#f7df1e" },
  { name: "React", color: "#61dafb" },
  { name: "Vue.js", color: "#4FC08D" },
  { name: "Angular", color: "#DD0031" },
  { name: "Node.js", color: "#339933" },
  { name: "TypeScript", color: "#007ACC" },
  { name: "Python", color: "#3776AB" },
  { name: "Django", color: "#092E20" },
  { name: "Flask", color: "#000000" },
  { name: "Java", color: "#007396" },
  { name: "Kotlin", color: "#0095D5" },
  { name: "Swift", color: "#FA7343" },
  { name: "PHP", color: "#777BB4" },
  { name: "Ruby", color: "#CC342D" },
  { name: "C#", color: "#239120" },
  { name: "C++", color: "#00599C" },
  { name: "Go", color: "#00ADD8" },
  { name: "Rust", color: "#DEA584" },
  { name: "Docker", color: "#2496ED" },
  { name: "Kubernetes", color: "#326CE5" },
  { name: "AWS", color: "#FF9900" },
  { name: "Azure", color: "#0078D4" },
  { name: "Google Cloud", color: "#4285F4" },
  { name: "Git", color: "#F05032" },
  { name: "GitHub", color: "#181717" },
  { name: "PostgreSQL", color: "#336791" },
  { name: "MySQL", color: "#4479A1" },
  { name: "MongoDB", color: "#47A248" },
  { name: "GraphQL", color: "#E10098" },
  { name: "HTML", color: "#e34c26" },
  { name: "CSS", color: "#264de4" },
  { name: "SASS", color: "#CC6699" },
  { name: "TailwindCSS", color: "#06B6D4" },
  { name: "Bootstrap", color: "#7952B3" },
  { name: "Next.js", color: "#000000" },
  { name: "Gatsby", color: "#663399" },
  { name: "Redux", color: "#764ABC" },
];
