// list of all the tags
export const tagList = [
  { name: "Beginner", color: "#FF7F50" },
  { name: "Intermediate", color: "#FFD700" },
  { name: "Advanced", color: "#8A2BE2" },
  { name: "Looking for Feedback", color: "#1E90FF" },
  { name: "Help Wanted", color: "#FF4500" },
  { name: "Documentation", color: "#DAA520" },
  { name: "Tutorial", color: "#ADFF2F" },
  { name: "Article", color: "#FF69B4" },
  { name: "Machine Learning", color: "#FFB500" },
  { name: "Data Science", color: "#4595B8" },
  { name: "Web Development", color: "#3E7BB6" },
  { name: "Front-end", color: "#FF4081" },
  { name: "Back-end", color: "#333333" },
  { name: "Full Stack", color: "#00D1A1" },
  { name: "DevOps", color: "#4CAF50" },
  { name: "Cloud Computing", color: "#FF5722" },
  { name: "Mobile Development", color: "#FFC107" },
];
